### ISSUE TITLE
关于使用的问题

### ISSUE THREAD

**Issue by Mr-xue** [huang-ju/jshare-react-native#1]
你好，看你描述这个库支持rn 0.6+，但是如何安装你这个库？
直接把你的库拉下来放到node_modules里面么

**Comment by FuzzyFade** [comment]
直接 npm 就可以，后面接 git 地址（https/ssh）就好了

**Comment by FuzzyFade** [comment]
或者 fork 后直接 release，直接拉 tar 就行了，这样还能快一点。

**Comment by huang-ju** [comment]
@FuzzyFade 感谢🙏
